remote_theme: pages-themes/minimal@v0.2.0
title: Chris Kalahiki
description: Personal website showcasing education, publications, work history, and projects
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics: 
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Jekyll settings
baseurl: ""
url: "https://chriskalahiki.github.io"
permalink: pretty
include: 
  - _pages

# Navigation structure
collections:
  pages:
    output: true
    permalink: /:collection/:name/