theme: jekyll-theme-minimal
title: Chris Kalahiki
description: Personal website showcasing education, publications, work history, and projects
logo: /assets/img/profile.jpg
show_downloads: false
google_analytics: 
plugins:
  - jekyll-seo-tag